### ISSUE TITLE
search gives unpredictable results

### ISSUE THREAD

**Issue by MortenHofft** [gbif/vocabulary#104]
minimum 3 letters required?

https://api.gbif.org/v1/vocabularies/EstablishmentMeans/concepts?limit=100&q=in&locale=en

will give no results despite a search for `int` will. Since the vocabularies are relatively small, at least in this case, then I suggest we make it less strict and just have it return a lot of values even if users only enter a single letter.

NB: we currently use search as suggest doesn't really work https://github.com/gbif/vocabulary/issues/102

**Comment by MortenHofft** [comment]
I just realise that it isn't a minimum number of letters issue. A search for `n` for example returns introduced. But a search for `in`does not.

https://api.gbif.org/v1/vocabularies/EstablishmentMeans/concepts?limit=100&q=n&locale=en

**Comment by marcos-lg** [comment]
@MortenHofft I can try to do a version without stop words and we test it. I think it will affect mostly to phrase queries but probably in the vocabularies they are not very common queries.

**Comment by marcos-lg** [comment]
I've deployed a version without stop words in DEV. I'm still testing it but it looks better:

https://api.gbif-dev.org/v1/vocabularies/EstablishmentMeans/concepts?limit=100&q=in&locale=en

**Comment by marcos-lg** [comment]
Deployed to PROD.
