### ISSUE TITLE
API function to find concept based on value

### ISSUE THREAD

**Issue by ManonGros** [gbif/vocabulary#142]
It would be great to have an API function/endpoint where I can find which concept a value matches to for a given vocabulary.

For example, I would like to know which concept `jeune` matches to in the life stage vocabulary. Right now I have to query all the labels for all the concept until I find the right one.
Instead, I would like to be able to do something like `https://api.gbif.org/v1/vocabularies/lifeStage/match?q=jeune` and be returned the concept for which the value matches (the value should be matched to any of the hidden or alternative or translation labels).

**Comment by CecSve** [comment]
This would be very helpful for users and institutions that may want to use a vocabulary to map their data prior to sharing it with GBIF

**Comment by marcos-lg** [comment]
We have a basic full-text search: https://api.gbif.org/v1/vocabularies/LifeStage/concepts?q=joven

I think `jeune` is not present in any label.

**Comment by ManonGros** [comment]
I am confused by that function, if use https://api.gbif.org/v1/vocabularies/Sex/concepts?q=male, I get several concepts. Is there a way to find the concept that the value `male` would match to?

**Comment by CecSve** [comment]
> I am confused by that function, if use https://api.gbif.org/v1/vocabularies/Sex/concepts?q=male, I get several concepts. Is there a way to find the concept that the value `male` would match to?

You get all the concepts of the vocabulary, it seems. Ideally, you should only get the concept that the verbatim value maps to (if the hidden value exists of course)

**Comment by marcos-lg** [comment]
That is a free-text search that matches any concept that has that value. I think what you want is a lookup endpoint but we don't have it (pipelines does a lookup but it's not an API endpoint). We could add it though.

**Comment by ManonGros** [comment]
I think having a lookup would be really helpful.

**Comment by CecSve** [comment]
+1

**Comment by CecSve** [comment]
> I think having a lookup would be really helpful.

+1

**Comment by marcos-lg** [comment]
I deployed a lookup endpoint in UAT.

It returns only the fields that match, for example, this matched the concept name:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=adult

This matched the spanish label:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=adulto

this matched a hidden label:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=A

this matched an alternative label:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=Newborn

you can also filter by language:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=adulto&lang=PT-pt
https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=adulto&lang=ES-es

and if the value is not found in that language but exists in English, the English match is returned:

https://api.gbif-uat.org/v1/vocabularies/LifeStage/concepts/lookup?value=newborn&lang=ES-es

@CecSve @ManonGros are you missing something or is there anything you want to change?

**Comment by marcos-lg** [comment]
I replace non-ascii characters with their equivalents but it seems that `pridol` doesn't exist. This works:

https://api.gbif-uat.org/v1/vocabularies/GeoTime/concepts/lookup?q=přídoli

**Comment by ManonGros** [comment]
Ha! Yes I probably did some wrong copy/pasting. Thanks for checking Marcos! The lookup looks good, it will be very helpful to have.

**Comment by marcos-lg** [comment]
Deployed to production. 

E.g.: https://api.gbif.org/v1/vocabularies/LifeStage/concepts/lookup?q=adulto

**Comment by marcos-lg** [comment]
Forgot to mention that this also works for the `latestRelease` endpoints, e.g.: https://api.gbif.org/v1/vocabularies/LifeStage/concepts/latestRelease/lookup?q=adulto

**Comment by CecSve** [comment]
Thank you! This super useful.
