### ISSUE TITLE
Corrections to GeoTime vocab

### ISSUE THREAD

**Issue by ljwalker** [gbif/vocabulary#161]
The startAge and endAge values in the _definitions_ for the following concepts are reversed (i.e. they should read "A time period from [startAge] to [endAge])":
- https://registry.gbif.org/vocabulary/GeoTime/concept/Valanginian
- https://registry.gbif.org/vocabulary/GeoTime/concept/Olenekian

Additionally:
- https://registry.gbif.org/vocabulary/GeoTime/concept/Ludlow: correct endAge = 423.0 (not 419.2)
- https://registry.gbif.org/vocabulary/GeoTime/concept/CambrianStage2: correct startAge = 529 & endAge = 521 (not 521-509)

**Comment by marcos-lg** [comment]
Thanks for reporting it! I just fixed it.
