### ISSUE TITLE
add HTTP headers for authenticated requests

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/vocabulary#25]
When a browser does authenticated requests it issues an OPTIONS preflight request to check for these headers:
`access-control-allow-headers`, `access-control-allow-methods`, `access-control-allow-origin`.

So accessing this directly: https://api.gbif-dev.org/v1/vocabularies?q=&limit=25&offset=0 works fine, but when called from the browser it gets a 403 on the preflight request.

I think this can be fixed by adding these headers to the endpoints 
`access-control-allow-headers: authorization`
`access-control-allow-methods: HEAD, GET, POST, DELETE, PUT, OPTIONS`
`access-control-allow-origin: *`

**Comment by asturcon** [comment]
Fixed in https://github.com/gbif/vocabulary/commit/33f960ee93dbeef4c964bcd2f6c3b7c172ccc269
