### ISSUE TITLE
Add API calls to retrieve parents and children

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/vocabulary#27]
Add `key` to query params for both 

`GET /vocabularies` and `GET /vocabularies/{vocabularyName}/concepts`

This is needed to retrieve `replacedBy` and for concepts and parent

Also add `parentKey` to query params for `GET /vocabularies/{vocabularyName}/concepts` in order to list all immediate child concepts

**Comment by asturcon** [comment]
Added the key to the query params. The parentKey in the list concepts was already added.

It's deployed in DEV. The documentation was updated too.
