### ISSUE TITLE
Too strict requirements for labels

### ISSUE THREAD

**Issue by MortenHofft** [gbif/vocabulary#33]
Currently below is not allowed and is a real example based on our translations:

Vocabulary - RANK
* COHORT: 
  * jp: コホート
  * zh: 群
* GREX: 
  * jp: 群
  * zh: ''

Chinese COHORT conflicts with Japanese GREX. This seems an unreasonable requirement to put on translators "you are not allowed to use a word someone else have used in another language for another concept".

I get that this is a useful requirement for interpretation, but in those cases we could instead 
* say that is unresolvable or 
* use the dataset language context as resolver. Falling back to english as a tie breaker if an english label is part of the conflict.

**Comment by asturcon** [comment]
Deployed in DEV

**Comment by asturcon** [comment]
Deployed in UAT
