### ISSUE TITLE
Use names instead of IDs when creating concepts

### ISSUE THREAD

**Issue by marcos-lg** [gbif/vocabulary#34]
To create a new concept we can use the vocabulary name instead of the id in order to link them. This way the clients can ignore the IDs and work only with names.

**Comment by asturcon** [comment]
@MortenHofft Now the vocabulary key is not required to create a concept thru the API.

Deployed in DEV and UAT.

**Comment by asturcon** [comment]
Only deployed in DEV (not in UAT yet)
