### ISSUE TITLE
Geodetic Datum - curation before uploading first vocabulary version

### ISSUE THREAD

**Issue by ManonGros** [gbif/vocabulary#71]
Here is a file to edit: https://drive.google.com/file/d/1dyMU5H1HHNHpgVaa8kmPkGi5esIae7_4/view?usp=sharing

**It contains:**

- the list of existing concepts
- a list of the values already mapped to the concepts (they are all in the **Hidden** sheet/tab for now)
- the GBIF verbatim values for this field that appear more than 10,000 times or in 5 or more datasets

**NB:** this particular version of the mapping is recent as I incorporated the work of @tucotuco. So I don't think there is a lot of work to be done.

Pease check instructions here: https://github.com/gbif/vocabulary/issues/70

**Comment by tucotuco** [comment]
I would like to continue to work on this one. I have the data ready for the labels in the "Concepts" sheet, I also have one correction in the "Hidden" sheet. In addition, I have the labels and mappings for every concept and hidden label in the GBIF snapshot from 2021-01-12, which added 232 distinct values of geodeticDatum since 2020-04-09. I would like to include them all rather than the arbitrary cut-off of popularity. The reason is that all of them are needed to do proper coordinate transformations to WGS84 in the pipeline. It seems silly to leave them out if I already have them. I have requested edit access to the sheet.

**Comment by tucotuco** [comment]
I just put the English labels for the Concepts. These all come from EPSG.ioand changed the one hidden mapping of "ETRS89 (~WGS84)" to 4258. I see the thumbs up from @ManonGros  on my previous comment, but will await an explicit confirmation before adding the other Concepts and hidden labels.

**Comment by ManonGros** [comment]
Thanks @tucotuco! you can go ahead with the rest.

**Comment by tucotuco** [comment]
I have finished updating the "Concepts" and "Hidden" sheets. I added a few more concepts and a lot more hidden alternatives. I removed the Hidden labels that mapped to concepts that had the same concept id and english label as there shouldn't be any duplication between those sets. I refrained from adding all of the unmappable nonsense (coordinates, integers out of range for epsg codes, etc.) that would have tripled the size of the table.

**Comment by tucotuco** [comment]
1. - [ ] Add English labels to the concepts.

2. Check the already mapped values in the Hidden sheet/tab:
- [ ] Correct any errors.
- [ ] When needed, move the mapped values from the Hidden sheet to the Concept sheet as an alternative label but do not add any new concept.
3. - [ ] Map as many verbatim values as possible and add them to the Concepts and Hidden sheet/tabs:
4. - [ ] Incorporate VertNet mapping to the Concepts and Hidden sheet/tabs if possible: https://github.com/VertNet/DwCVocabs/blob/master/vocabs/
5. - [ ] Incorporate the ALA mapping to the Concepts and Hidden sheet/tabs if possible.

**Comment by CecSve** [comment]
I will begin to finalize this vocabulary. 
- [ ] map remaining verbatim values
This vocabulary is only used for internal processing and inference of verbatim values to EPSG: standards - the UI/interpreted field will always show WGS 84 (as it does now), so it is a support for the re-projecting step.

**Comment by tucotuco** [comment]
Hi @CecSve . I have a complete mapping of 82707 distinct v_geodeticdatum to epsg codes as of the 2022-07-14 snapshot.  The mappings can be found [here](https://github.com/VertNet/DwCVocabs/blob/master/vocabs/geodeticDatum.csv). Let me know if that is sufficient, and if not, I can fill out the sheets the way vocabularies have normally been done.

**Comment by CecSve** [comment]
Perfect, thanks @tucotuco. I think that would be sufficient. Should I just go ahead and add them to the hidden values and remove any duplicates then? I have added some unmapped verbatim values from the verbatim values sheet to the hidden values sheet - we might want to check if the are covered in the snapshots (I would think they would be?).

**Comment by CecSve** [comment]
Ok, sounds good. I will replace it and prepare it for upload.

**Comment by CecSve** [comment]
From our [portal feedback system](https://github.com/gbif/portal-feedback/issues/4388).

**Comment by tucotuco** [comment]
Where does the copy of this vocabulary used by the pipeline live? There is interest by the TDWG Biodiversity Data Quality Interest Group to actually be able to access the vocabulary for lookups to EPSG codes.

**Comment by marcos-lg** [comment]
This vocabulary hasn't been created in live yet and therefore it's still not used.

**Comment by tucotuco** [comment]
@marcos-lg But is there a publicly accessible copy of it that people can refer to? It is immensely useful.

**Comment by marcos-lg** [comment]
Only the google sheet I believe https://drive.google.com/file/d/1dyMU5H1HHNHpgVaa8kmPkGi5esIae7_4/view?usp=sharing

**Comment by CecSve** [comment]
PNG94 is part of the vocabulary in UAT: https://registry.gbif-uat.org/vocabulary/GeodeticDatum. Should we move this vocabulary to prod?

**Comment by CecSve** [comment]
@tucotuco I think I need your help. I am trying to get the vocabulary uploaded and have some issues with the concepts and labels - the labels have to be unique but some appear in two concepts:

- SAD69 is a value in Label_en for two concepts: 4618 and 4291
- GDA94 is a value in Label_en for two concepts: 4938 and 4283
- NAD27 is a value in Label_en for two concepts: 4367 (typo?) and 4267

Can it somehow be specified how the differ, if it is not a mistake that they appear twice?

**Comment by tucotuco** [comment]
@CecSve 
epsg:4291 is a deprecated version of 4618. Both are for SAD69 in Brazil.

epsg:4938 is a valid coordinate reference system for decimal degrees, epsg:4283 is not. All mappings to 4283 should actually be to 4938 instead.

NAD27 should be epsg:4267 as epsg:4367 is a deprecated coordinate reference system for REGVEN (3D).

I hope that helps.

**Comment by CecSve** [comment]
Thank you @tucotuco. 

For the latter two I will; 

- change the mapping of 4283 to 4938 in the hidden values file and remove the epsg:4283 concept. 
- change the Label_en for epsg:4367 to REGVEN (3D)

For the first, I propose to change the Label_en to `SAD69 - Brazil` for [4618](https://epsg.io/?q=4618) so the labels are unique. Would that work for you?

**Comment by tucotuco** [comment]
Yes, that all will work..

**Comment by CecSve** [comment]
The vocabulary has now been uploaded to PROD: https://registry.gbif.org/vocabulary/GeodeticDatum.
