### ISSUE TITLE
Kingdom - curation before uploading first vocabulary version

### ISSUE THREAD

**Issue by ManonGros** [gbif/vocabulary#76]
Here is a file to edit: https://drive.google.com/file/d/1sQrhCykgwL1VHw_7UoQX83F7gV51xr8R/view?usp=sharing

**It contains:**

- the list of existing concepts
- a list of the values already mapped to the concepts (they are all in the **Hidden** sheet/tab for now)
- the GBIF verbatim values for this field that appear more than 10,000 times or in 5 or more datasets

Pease check instructions here: https://github.com/gbif/vocabulary/issues/70

**Comment by CecSve** [comment]
I have gone through this vocabulary now - I did not check with ALA concepts (do not know how to access them - do one of you have a link?). So now I guess it is internal review in DP before talking to Marcos on how to add it to the registry.

**Comment by timrobertson100** [comment]
> I did not check with ALA concepts ... how to access them

Since this is for occurrence processing I think we can just see what they have in their occurrence data. From the [ALA search](https://biocache.ala.org.au/occurrences/search?q=*%3A*), you can click customize your filters, add Kingdom and then here is a screenshot of the concepts they have:

<img width="583" alt="Screenshot 2022-06-10 at 13 29 37" src="https://user-images.githubusercontent.com/237221/173055726-40d0c5f9-183b-4c2c-80be-81688aab53f0.png">

**Comment by CecSve** [comment]
I have added ALA concepts: Protista, Prokaryote (Domain), Eukaryota (Domain) and Not supplied. Archaea and Bacteria are also domains. Since we include Domains, I have added parents (Eukaryota and Prokaryote) to some of the Kingdoms based on [the following system](https://en.wikipedia.org/wiki/Kingdom_(biology)#Seven_kingdoms) which should be in adherence to the consensus of CoL.

**Comment by CecSve** [comment]
@ahahn-gbif I can for some reason not assign you to this issue as an reviewer but hopefully this ping works

**Comment by ahahn-gbif** [comment]
I am getting uncertain about the ways we will want to use this, and what criteria we need to meet to make sure that function is fulfilled. 

There now are 11 concepts, some of which are, as you say, not really kingdoms, but higher ranks. We also have more concepts included than we use at GBIF.org to accomodate ALA. If we extend the concepts list beyond what we use for kingdoms today (https://www.gbif.org/species/search?rank=KINGDOM), what impact will that have on
- ingestion
- population of search options
- matching against the backbone taxonomy
?

The extended list allows to match more occurrences to concepts, but does it have adverse effects in other places?
@mdoering and @timrobertson100 , how did we decide on the 8+1 values we have for kingdoms to date, do you remember? Is it a requirement to keep this list of concepts stable to not disrupt interpretation in different places, or do we have options to pick a subset of concepts for GBIF use while ignoring others (ALA-specifics: Eukaryota, Protista; superkingdoms and domains)?

**Comment by CecSve** [comment]
https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Kingdom.java current vocabulary

**Comment by ahahn-gbif** [comment]
On second thoughts: this concept seems to relate to taxon names only, not to occurrences. Or am I overlooking anything?

**Comment by mdoering** [comment]
The GBIF kingdoms come straight from COL. A kingdom vocabulary should follow whatever we have in our backbone closely as concepts and not add more. It is also a hardcoded Java enumeration in the old ChecklistBank code which is used for checklist and occurrence matching. We cannot just change the number of concepts without a careful review of the code base.

Said that COL already started to change their kingdoms...

**Comment by CecSve** [comment]
> Said that COL already started to change their kingdoms...

How so? And then this would affect GBIFs backbone I suppose in the next update? In that case, it might make more sense to wait with this vocabulary until the changes in CoL is finished.

**Comment by mdoering** [comment]
We have decided not to follow those changes in the Backbone for now. It is mostly Viruses for now:
https://www.catalogueoflife.org

**Comment by ahahn-gbif** [comment]
Thanks @mdoering! In that case we should stick with the kingdom concept list as-is, and map as best is possible

**Comment by CecSve** [comment]
I have revised the concepts and the hidden tab to only contain the kingdoms as-is. Please review when you have time @ahahn-gbif

**Comment by ahahn-gbif** [comment]
Change log:
- I mapped the "artificial"/polyphyletic groups that do not match any of the concepts exactly to incertae_sedis (monera, algae, others)
- deleted duplicate rows
- **open question on application**: should the hidden value mapping really include values that are not at the same rank (or close equivalent), or would we not rather leave those open/unmapped? 

E.g.: is a mapping of "Aves", "Insects" or "Fishes" to "Animalia" as a kingdom vocabulary equivalent meaningful in this context, or should it be avoided/removed? It could lead to conflicts during taxon name parsing and interpretation, and is not factually correct. If a data publisher mapped "Hepaticae" to the kingdom, do we want to interpret this as meaning "Plantae", or do we want to throw an error and give it back for correction?  I would value some input here from someone more familiar with the intended use of the vocabulary - @mdoering maybe?

**Comment by mdoering** [comment]
I am not sure how we plan to make use of the vocabulary. The old checklistbank code has a KingdomUtils class that keeps a matrix of how all kingdoms can overlap with each other. So the matching knows Chromista can also be Animalia, Fungi or Plants in some cases. That would be good for the "artificial" groups too I suppose. As incertae sedis matches any kingdom I guess that mapping is ok. 

I dont think we should be mapping entirely different ranks that are never ever used as kingdoms.

**Comment by ahahn-gbif** [comment]
Thanks, @mdoering! @CecSve, in that case I would recommend to remove the mappings to anything that is not a kingdom equivalent (or close enough to one of the other systems), and focus on the application in occurrence ingestion (values we get from publishers that we need to make best sense of), thanks!

**Comment by CecSve** [comment]
Change log:

- Removed mapping of lower level taxonomy ranks 
- Removed Metazoa from the Hidden labels as it is an alternative label
- Added Biota as a value and mapped it to Incertae_sedis (to accomodate the Kingdom = Biota provided by many OBIS datasets and which are now mapped to Genus = Biota)

I will go ahead and upload the vocabulary now.

**Comment by CecSve** [comment]
Further work:

- removed hidden labels that were the same as the concept (not upper case and special characters sensitive so those were removed too)
- tested different encoding styles to keep as many special characters when needed (no changes to standard procedure)
- Incertae sedis concept renamed to IncertaeSedis for the tool to register it
- tested upload 

Will upload the vocbulary now.
