### ISSUE TITLE
TaxonRank - curation before uploading first vocabulary version

### ISSUE THREAD

**Issue by ManonGros** [gbif/vocabulary#88]
Here is a file to edit: https://drive.google.com/file/d/1YG5dy3rDf3BSuy7p6MhP7weNw5o-jTE8/view?usp=sharing

**It contains:**

- the list of existing concepts
- a list of the values already mapped to the concepts (they are all in the **Hidden** sheet/tab for now)
- the GBIF verbatim values for this field that appear more than 10,000 times or in 5 or more datasets

Pease check instructions here: https://github.com/gbif/vocabulary/issues/70

**Comment by pzermoglio** [comment]
I'd like to work on this one, I've requested access.
Thanks

**Comment by mdoering** [comment]
Using the vocab server for cleaning the occurrences consistently makes a lot of sense to me.
The enumeration is actually part of the [name parser API](https://github.com/gbif/name-parser/blob/master/name-parser-api/src/main/java/org/gbif/nameparser/api/Rank.java#L35) which is used in its latest version in checklistbank.org, but also in GBIF CLB - though it might be slightly older.

The ordered rank vocabulary is exposed in https://api.checklistbank.org/vocab/rank with other properties. COL maintains a dictionary file like the old GBIF ones here: https://github.com/CatalogueOfLife/backend/blob/master/parser/src/main/resources/parser/dicts/rank.csv

**Comment by CecSve** [comment]
> I'd like to work on this one, I've requested access. Thanks

Hi @pzermoglio I would like to begin working on this as well - let me know if you are still working on this and I should leave it be.

**Comment by CecSve** [comment]
> 

@mdoering I am working on this vocabulary now. Just to make sure I get the hierarchies right - is the sections in [the name parser](https://github.com/gbif/name-parser/blob/master/name-parser-api/src/main/java/org/gbif/nameparser/api/Rank.java#L35) organised by level? If so, is that the setup we should use or should I use [checklistbank ](https://api.checklistbank.org/vocab/rank) levels? 

As an example, parvphylum is in checklistbank under phylum, while in the nameparser I would interpret it to be under infraphylum.

**Comment by CecSve** [comment]
Another thing - in checklistbank, the higher taxonomy of phylum, e.g. superphylum has majorrank=phylum. Would it technically not be more correct to have the parent rank (majorrank I assume) = kingdom?

**Comment by mdoering** [comment]
I dont see the difference with parvphylum. In both resources it comes after infraphylum. The CLB vocabulary should be exactly the same as the name parser one, but offers a few more properties like majorrank which is the base rank. Any super/sub/xxxphylum ranks will point to phylum. It classifies them into the linnean ranks mostly.

And we do use all those ranks, just not in the backbone.

**Comment by CecSve** [comment]
Thank you @mdoering. Not sure where I can see the nearest parent in either of the resources, unless you refer to the sequence of terms in both cases. I realise the sublevels would return the ranks we actually deal with in GBIF, but if I understand you correctly, then we _do_ want to capture the nestedness of the terms. In the new vocabulary we will capture it as parents.

What are you thoughts on: 
> Another thing - in checklistbank, the higher taxonomy of phylum, e.g. superphylum has majorrank=phylum. Would it technically not be more correct to have the parent rank (majorrank I assume) = kingdom?

**Comment by mdoering** [comment]
yes, its the sequence that defines the order of the ranks. With a few exceptions that are do not fit into the ordering:

Not sure how to model this best in a nested vocabulary. Do you have both a sibling sequence and parent?
Maybe simply drop majorrank and just capture the sequence which is the most important part. As we only plan to use this for mapping occurrence rank values hierarchy and even the sequence does not matter much

**Comment by CecSve** [comment]
I have created a nested structure, when it is possible, in the vocabulary now. The super* ranks now point to the higher, interpreted, rank, e.g. superkingdoms' parent is domain, superphylums' parent is kingdom, etc. :

<html><body>
<google-sheets-html-origin><style type="text/css"></style>

Concept | Parent
-- | --
DOMAIN |  
REALM |  
SUBREALM | REALM
SUPERKINGDOM | DOMAIN
KINGDOM | SUPERKINGDOM
SUBKINGDOM | KINGDOM
INFRAKINGDOM | SUBKINGDOM
SUPERPHYLUM | KINGDOM
PHYLUM | SUPERPHYLUM
SUBPHYLUM | PHYLUM
INFRAPHYLUM | SUBPHYLUM
PARVPHYLUM | INFRAPHYLUM
MICROPHYLUM | PARVPHYLUM
NANOPHYLUM | MICROPHYLUM
GIGACLASS | PHYLUM
MEGACLASS | GIGACLASS


</body>
</html>

**Comment by mdoering** [comment]
Why is the parent of gigaclass phylum? Should it not be Nanophylum instead?

**Comment by CecSve** [comment]
It could be, but then we should consistently refer to the higher level when we can - it is not always possible since it depends on the field sometimes, for example botany and zoology use the same terms but at different hierarchical levels, as you also mention in the name parser code. I am considering to leave the highest rank of each subset level unparented - it seems it is what you did for the name parser?

**Comment by CecSve** [comment]
But based on the name parser, kingdoms parent should be domain, which reminds me of the discussion with OBIS on how we best resolve some of their datasets extensive use of domain

**Comment by CecSve** [comment]
Yes, good point. I guess where it really matters is how we treat the synonyms/hidden labels. As we discussed previously over email (OBIS using superdomain in many datasets), we currently do not use a hidden label for [superdomain = domain](https://github.com/CatalogueOfLife/backend/blob/master/parser/src/main/resources/parser/dicts/rank.csv). I could add it here, but there might be other synonyms at different levels that need interpretation... I do not have the full overview.

**Comment by CecSve** [comment]
Ok, @jhnwllr I will hand this vocabulary over to you now for review.

Besides the values that are not interprebable, there are some things I have left unmapped but could be discussed:

- Hybrids (hybrid etc.) and related values (notho*) are not mapped although they are mapped in the [CoL dictionary file](https://github.com/CatalogueOfLife/backend/blob/master/parser/src/main/resources/parser/dicts/rank.csv). I am unsure whether this affects how the names are interpreted (51 datasets, 22,207 occurrences).
- f, f. etc. and d, d. etc. are not mapped as they could relate to at least two different ranks.
- alpha, beta, epsilon etc. which are bacterial clade denominators are not mapped since it technically does not refer to a rank.
- Clade is mapped as unranked.
- We currently do not map any values to the concept OTHER since the description is 

> Any other rank we cannot map to this enumeration

and we do not have anything that clearly defines a rank.

**Comment by CecSve** [comment]
I will afterwards add the VertNet and ALA mappings if needed.

**Comment by mdoering** [comment]
> * Hybrids (hybrid etc.) and related values (notho*) are not mapped although they are mapped in the [CoL dictionary file](https://github.com/CatalogueOfLife/backend/blob/master/parser/src/main/resources/parser/dicts/rank.csv). I am unsure whether this affects how the names are interpreted (51 datasets, 22,207 occurrences).

we treat hybrid not via the rank, but via a special "notho" property. So nothovariety is just a variety. We therefore mapped them so far all to their respective regular rank.

**Comment by CecSve** [comment]
Thank you for the explanation - it makes sense. I will include mapping to the rank defined in the notho* values then.

**Comment by CecSve** [comment]
- [ ] move alternative labels to hidden labels

**Comment by jhnwllr** [comment]
Here are my comments so far, but I am by no means a taxonomist, so feel free to disagree. 

**cv.** I think should be mapped to concept CULTIVAR 
**Race** I think should be mapped to concept RACE
**fo.**  I think should be mapped to concept FORM
**microspecies** feels like RACE, VARIETY
**species pro parte** feels like SPECIES
**species sensu lato** feels like SPECIES

**Comment by mdoering** [comment]
microspecies is hard to map, I would do INFRASUBSPECIFIC_NAME or OTHER

**Comment by CecSve** [comment]
- [ ] cv. to cultivar
- [ ] race to race
- [ ] fo. to form
- [ ] microspecies to other
- [ ] species pro parte to species
- [ ] species sensu lato to species
- [ ] make hidden_server sheet 
      - [ ] copy hidden label and updated concept
      - [ ] remove duplicate rows

**Comment by CecSve** [comment]
TaxonRank vocabulary has now been uploaded.
