### ISSUE TITLE
Add Spanish to establishmentMeans

### ISSUE THREAD

**Issue by timrobertson100** [gbif/vocabulary#93]
The [establishmentMeans](https://registry.gbif.org/vocabulary/EstablishmentMeans) vocabulary is in the production database and ready for Spanish translation.

@leobuitrago2 
Please can you add Spanish translation for _only_ the label and definition of each concept and the vocabulary itself?
Please can you self-assign this issue when you accept the invitation to this repository?
Please log issues for the UI in https://github.com/gbif/registry-console

**Comment by qgroom** [comment]
Actually Spanish and Dutch translations already exist https://docs.google.com/spreadsheets/d/1qsFIM60VS6ZUAoE9sLgoFd88ib5qvAoABsNSb4Ye9dE/edit?usp=sharing

**Comment by timrobertson100** [comment]
Thanks @qgroom 

They need to be tweaked ever so slightly because these aren't the SKOS scheme but follow the originals closely. I also reformatted some of the labelling using brackets instead of colons since we have a hierarchy here. A native speaker will be able to port those easily though.

If it exists, can you please link the spreadsheet you have for https://github.com/gbif/vocabulary/issues/94 as well?

**Comment by leobuitrago2** [comment]
ok @timrobertson100, thanks for the instructions.

Please confirm if the changes should be done in the [production UI](https://registry.gbif.org/vocabulary/EstablishmentMeans) or [UAT](https://registry.gbif-uat.org/vocabulary/EstablishmentMeans).

**Comment by timrobertson100** [comment]
> @timrobertson100 please confirm if the changes should be done in the production UI or UAT.

Production @leobuitrago2. These are new and small, so it is safe to do and it's good to learn the behaviour of changes made there in a safe way.

**Comment by leobuitrago2** [comment]
Hi @timrobertson100 sorry for my late reply here. I've finished the documentation in the Production UI of the labels in Spanish for each concept, everything works fine! I just found a [minor issue](https://github.com/gbif/registry-console/issues/377) in the registry. I hope to continue working with the other vocabularies. Greetings!
