### ISSUE TITLE
Add Pathway vocabulary

### ISSUE THREAD

**Issue by timrobertson100** [gbif/vocabulary#95]
In order to bring in the new Darwin Core terms, we need to create a vocabulary for [pathway](http://rs.tdwg.org/dwcpw/values.htm).

Because this has 53 values it will be tedious to enter manually, so I will work with Leo to get the English and Spanish versions ready in a spreadsheet before we import it.

The [English sheet](https://docs.google.com/spreadsheets/d/1bbmk_5xM9t27YWMaW40zP7ELoMs11ncrWNPs4WepOCw/edit#gid=0) is ready for Spanish translation. This only has a concepts column because it is a new vocabulary.

CC @leobuitrago2 if he wishes to contribute before we import?

**Comment by timrobertson100** [comment]
The UAT registry has a test version (English only) here 
https://registry.gbif-uat.org/vocabulary/PathwayTest1/concepts

**Comment by leobuitrago2** [comment]
I will be glad to contribute here @timrobertson100. I've already requested you access to the [English sheet](https://docs.google.com/spreadsheets/d/1bbmk_5xM9t27YWMaW40zP7ELoMs11ncrWNPs4WepOCw/edit#gid=0) to work in the Spanish translation. Do you want to work directly in the spreadsheet first and then release it in [UAT](https://registry.gbif-uat.org/vocabulary/PathwayTest1/concepts)?

**Comment by timrobertson100** [comment]
Thanks @leobuitrago2 

Yes, this one we'll verify in UAT before running in production. You get one chance to import, after which it is manual editing concept by concept currently. This is large enough that is too painful to do in the UI currently. 
The other two (establishmentMeans and degreeOfEstablishment) we are editing in the UI in production.

**Comment by timrobertson100** [comment]
In production
