### ISSUE TITLE
API release is not immutable

### ISSUE THREAD

**Issue by timrobertson100** [gbif/vocabulary#98]
When we release a vocabulary we push JSON to nexus, such as [this example](https://repository.gbif.org/service/rest/repository/browse/releases/org/gbif/vocabulary/export/LifeStage/1.0.3/).

However, this returns a different JSON document from the [GBIF API]( https://api.gbif.org/v1/vocabularies/LifeStage/releases/1.0.3/export) for the same release. This one has a "tags".

This might be by design (e.g. to allow a UI to compare content across releases while still allowing new features to be added) but I think it might cause some confusion. Once released, it would be more intuitive to always treat released vocabularies as immutable. 

Discovered in production [here](https://github.com/gbif/pipelines/issues/572)

**Comment by marcos-lg** [comment]
Fixed and deployed to PROD
